### ISSUE TITLE
训练出现RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Double-bear** [alibaba/Megatron-LLaMA#10]
我训练llama2-7b模型，出现下面的错误：
```
LocalFileSystem: /code/xx/LLM_mine/reference/Megatron-LLaMA/model/llama2_7b 
LocalFileSystem: /code/xx/LLM_mine/reference/Megatron-LLaMA/model/llama2_7b 
Checkpoint not found for file release/mp_rank_00_001_dp_000/ at root /code/xx/LLM_mine/reference/Megatron-LLaMA/model/llama2_7b
Checkpoint not found for file release/mp_rank_01_001_dp_000/ at root /code/xx/LLM_mine/reference/Megatron-LLaMA/model/llama2_7b
WARNING: could not find the checkpoint file model_optim_rng.pt at root /code/xx/LLM_mine/reference/Megatron-LLaMA/model/llama2_7b.release:True, iteration:0
WARNING: could not find the checkpoint file model_optim_rng.pt at root /code/xx/LLM_mine/reference/Megatron-LLaMA/model/llama2_7b.release:True, iteration:0
/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:2387: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:2387: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
  warnings.warn(
(min, max) time across ranks (ms):
    load-checkpoint ................................: (1.53, 1.56)
(min, max) time across ranks (ms):
    model-and-optimizer-setup ......................: (1476.74, 1476.78)
    train/valid/test-data-iterators-setup ..........: (1404.95, 1466.99)
/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:2849: UserWarning: torch.distributed._reduce_scatter_base is a private function and will be deprecated. Please use torch.distributed.reduce_scatter_tensor instead.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:2849: UserWarning: torch.distributed._reduce_scatter_base is a private function and will be deprecated. Please use torch.distributed.reduce_scatter_tensor instead.
  warnings.warn(
Creating gradient buffer. Created: 1
Creating gradient buffer. Created: 2
Creating gradient buffer. Created: 3
Creating gradient buffer. Created: 1
Creating gradient buffer. Created: 2
Creating gradient buffer. Created: 3
/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [4,0,0] Assertion `t  >= 0 && t <  n_classes` failed.
/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [6,0,0] Assertion `t  >= 0 && t <  n_classes` failed.
/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [8,0,0] Assertion `t  >= 0 && t <  n_classes` failed.
/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [9,0,0] Assertion `t  >= 0 && t <  n_classes` failed.
/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [10,0,0] Assertion `t  >= 0 && t <  n_classes` failed.
/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [12,0,0] Assertion `t  >= 0 && t <  n_classes` failed.
/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [15,0,0] Assertion `t  >= 0 && t <  n_classes` failed.
/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [17,0,0] Assertion `t  >= 0 && t <  n_classes` failed.
/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [18,0,0] Assertion `t  >= 0 && t <  n_classes` failed.
/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [19,0,0] Assertion `t  >= 0 && t <  n_classes` failed.
/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [20,0,0] Assertion `t  >= 0 && t <  n_classes` failed.
/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [21,0,0] Assertion `t  >= 0 && t <  n_classes` failed.
/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [22,0,0] Assertion `t  >= 0 && t <  n_classes` failed.
/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [24,0,0] Assertion `t  >= 0 && t <  n_classes` failed.
/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [26,0,0] Assertion `t  >= 0 && t <  n_classes` failed.
/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [28,0,0] Assertion `t  >= 0 && t <  n_classes` failed.
/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [29,0,0] Assertion `t  >= 0 && t <  n_classes` failed.
/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [30,0,0] Assertion `t  >= 0 && t <  n_classes` failed.
/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [31,0,0] Assertion `t  >= 0 && t <  n_classes` failed.
Traceback (most recent call last):
  File "/code/xx/LLM_mine/reference/Megatron-LLaMA/pretrain_llama.py", line 119, in < module >
    pretrain(train_valid_test_datasets_provider, model_provider,
  File "/code/xx/LLM_mine/reference/Megatron-LLaMA/megatron/training.py", line 153, in pretrain
    iteration = train(forward_step_func,
  File "/code/xx/LLM_mine/reference/Megatron-LLaMA/megatron/training.py", line 711, in train
    train_step(forward_step_func,
  File "/code/xx/LLM_mine/reference/Megatron-LLaMA/megatron/training.py", line 426, in train_step
    losses_reduced = forward_backward_func(
  File "/code/xx/LLM_mine/reference/Megatron-LLaMA/megatron/core/pipeline_parallel/schedules.py", line 1023, in forward_backward_pipelining_without_interleaving
    send_backward_recv_forward(
  File "/code/xx/LLM_mine/reference/Megatron-LLaMA/megatron/core/pipeline_parallel/schedules.py", line 873, in send_backward_recv_forward
    input_tensor = p2p_communication.send_backward_recv_forward(
  File "/code/xx/LLM_mine/reference/Megatron-LLaMA/megatron/core/pipeline_parallel/p2p_communication.py", line 374, in send_backward_recv_forward
    input_tensor, _ = _communicate(
  File "/code/xx/LLM_mine/reference/Megatron-LLaMA/megatron/core/pipeline_parallel/p2p_communication.py", line 240, in _communicate
    torch.cuda.synchronize()
  File "/opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py", line 566, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[W CUDAGuardImpl.h:124] Warning: CUDA warning: device-side assert triggered (function destroyEvent)
[W CUDAGuardImpl.h:124] Warning: CUDA warning: device-side assert triggered (function destroyEvent)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 158) of binary: /opt/conda/bin/python
ERROR:torch.distributed.elastic.agent.server.api:Error waiting on exit barrier. Elapsed: 302.340993642807 seconds
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 906, in _exit_barrier
    store_util.barrier(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/utils/store.py", line 78, in barrier
    synchronize(store, data, rank, world_size, key_prefix, barrier_timeout)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/utils/store.py", line 64, in synchronize
    agent_data = get_all(store, rank, key_prefix, world_size)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/utils/store.py", line 34, in get_all
    data = store.get(f"{prefix}{idx}")
RuntimeError: Socket Timeout
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 33, in < module >
    sys.exit(load_entry_point('torch==1.13.1', 'console_scripts', 'torchrun')())
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```
我先用模型转换的脚本将llama2-7b从huggingface转到megatron，发现转完以后格式和代码中要读的不太一样：
![image](https://github.com/alibaba/Megatron-LLaMA/assets/38214501/3b9d0f90-f2ec-4343-8b25-27ff1cf460d3)
报错了路径显示不一致：
```
Checkpoint not found for file release/mp_rank_00_001_dp_000/ at root /code/xx/LLM_mine/reference/Megatron-LLaMA/model/llama2_7b
Checkpoint not found for file release/mp_rank_01_001_dp_000/ at root /code/xx/LLM_mine/reference/Megatron-LLaMA/model/llama2_7b
```
之后训练就出现了上述的错误，请问这种问题应该怎么解决？

**Comment by li-yi-dong** [comment]
May you post your launching script?

**Comment by Double-bear** [comment]
> May you post your launching script?

hi @li-yi-dong .this is my script:
```
python /code/xx/LLM_mine/reference/Megatron-LLaMA/tools/checkpoint_conversion/llama_checkpoint_conversion.py \
--load_path "/code/xx/LLM_mine/model/LLama2/Llama2_7b/llama2_7b" \
--save_path "/code/xx/LLM_mine/reference/Megatron-LLaMA/model/llama2_7b" \
--target_tensor_model_parallel_size 2 \
--target_pipeline_model_parallel_size 2 \
--target_data_parallel_size 1 \
--target_params_dtype "fp16" \
--make_vocab_size_divisible_by 1 \
--print-checkpoint-structure \
--megatron-path "/code/xx/LLM_mine/reference/Megatron-LLaMA"
```
and i also met another problem :
```
LocalFileSystem: /code/xiongxiong/LLM_mine/reference/Megatron-LLaMA/model/llama2_7b 

LocalFileSystem: /code/xiongxiong/LLM_mine/reference/Megatron-LLaMA/model/llama2_7b 

loading checkpoint from root /code/xiongxiong/LLM_mine/reference/Megatron-LLaMA/model/llama2_7b, release: True, iteration: 0

Traceback (most recent call last):

  File "/code/xiongxiong/LLM_mine/reference/Megatron-LLaMA/pretrain_llama.py", line 119, in < module >

    pretrain(train_valid_test_datasets_provider, model_provider,

  File "/code/xiongxiong/LLM_mine/reference/Megatron-LLaMA/megatron/training.py", line 112, in pretrain

    model, optimizer, opt_param_scheduler = setup_model_and_optimizer(

  File "/code/xiongxiong/LLM_mine/reference/Megatron-LLaMA/megatron/training.py", line 384, in setup_model_and_optimizer

    args.iteration = load_checkpoint(model, optimizer, opt_param_scheduler, load_dir=args.checkpoint_dir_name)

  File "/code/xiongxiong/LLM_mine/reference/Megatron-LLaMA/megatron/checkpointing.py", line 721, in load_checkpoint

    _load_common_from_state_dict(args, release, state_dict, model, strict=strict)

  File "/code/xiongxiong/LLM_mine/reference/Megatron-LLaMA/megatron/checkpointing.py", line 856, in _load_common_from_state_dict

    model[0].load_state_dict(state_dict["model"], strict=strict)

  File "/code/xiongxiong/LLM_mine/reference/Megatron-LLaMA/megatron/model/distributed.py", line 71, in load_state_dict

    self.module.load_state_dict(state_dict, strict=strict)

  File "/code/xiongxiong/LLM_mine/reference/Megatron-LLaMA/megatron/model/module.py", line 199, in load_state_dict

    self.module.load_state_dict(state_dict, strict=strict)

  File "/code/xiongxiong/LLM_mine/reference/Megatron-LLaMA/megatron/model/llama_model.py", line 154, in load_state_dict

    self.lm_head.load_state_dict(state_dict['lm_head'], strict=strict)

KeyError: 'lm_head'

load_common_from_state_dict: Could not find arguments in the checkpoint ...

Traceback (most recent call last):

  File "/code/xiongxiong/LLM_mine/reference/Megatron-LLaMA/pretrain_llama.py", line 119, in < module >

    pretrain(train_valid_test_datasets_provider, model_provider,

  File "/code/xiongxiong/LLM_mine/reference/Megatron-LLaMA/megatron/training.py", line 112, in pretrain

    model, optimizer, opt_param_scheduler = setup_model_and_optimizer(

  File "/code/xiongxiong/LLM_mine/reference/Megatron-LLaMA/megatron/training.py", line 384, in setup_model_and_optimizer

    args.iteration = load_checkpoint(model, optimizer, opt_param_scheduler, load_dir=args.checkpoint_dir_name)

  File "/code/xiongxiong/LLM_mine/reference/Megatron-LLaMA/megatron/checkpointing.py", line 721, in load_checkpoint

    _load_common_from_state_dict(args, release, state_dict, model, strict=strict)

  File "/code/xiongxiong/LLM_mine/reference/Megatron-LLaMA/megatron/checkpointing.py", line 856, in _load_common_from_state_dict

    model[0].load_state_dict(state_dict["model"], strict=strict)

  File "/code/xiongxiong/LLM_mine/reference/Megatron-LLaMA/megatron/model/distributed.py", line 71, in load_state_dict

    self.module.load_state_dict(state_dict, strict=strict)

  File "/code/xiongxiong/LLM_mine/reference/Megatron-LLaMA/megatron/model/module.py", line 199, in load_state_dict

    self.module.load_state_dict(state_dict, strict=strict)

  File "/code/xiongxiong/LLM_mine/reference/Megatron-LLaMA/megatron/model/llama_model.py", line 154, in load_state_dict

    self.lm_head.load_state_dict(state_dict['lm_head'], strict=strict)

KeyError: 'lm_head'
```
I restarted my task, and both of these issues have occurred.
and I used torch.load to load the state_dict in megatron, there is no key named 'lm_head' indeed.
I'm not quite sure where the problem lies.

**Comment by li-yi-dong** [comment]
> May you post your launching script?

The script that launching the training.

**Comment by Double-bear** [comment]
> > May you post your launching script?
> 
> The script that launching the training.

sry @li-yi-dong this is my training script:
```
#!/bin/bash

DATASET_1="/code/konglingkai/02LLM/data/megatron/llama2_wudao/pretrain_6_text_document"
# DATASET_2="<PATH TO THE SECOND DATASET>"
# DATASET_3="<PATH TO THE THIRD DATASET>"
DATASET="1.0 ${DATASET_1}"
# 0.3 ${DATASET_2} 0.5 ${DATASET_3}

TP_SIZE=2
PP_SIZE=2
WORLD_SIZE=4
MICRO_BATCH_SIZE=2
# The int is the number of micro steps of gradient accumulation
GLOBAL_BATCH_SIZE=$((($WORLD_SIZE * $MICRO_BATCH_SIZE) / ($TP_SIZE * $PP_SIZE) * 8))
# GLOBAL_BATCH_SIZE=128

JOB_NAME="LLaMA_tp${TP_SIZE}_pp${PP_SIZE}_mbs${MICRO_BATCH_SIZE}_gpus${WORLD_SIZE}"

LOAD_CHECKPOINT_PATH="/code/xx/LLM_mine/reference/Megatron-LLaMA/model/llama2_7b"
SAVE_CHECKPOINT_PATH="/code/xx/LLM_mine/reference/Megatron-LLaMA/output/llama2_7b"
TOKENIZER_PATH="/code/xx/LLM_mine/reference/Megatron-LLaMA/model/llama2_7b"
TENSORBOARD_DIR="/code/xx/LLM_mine/reference/Megatron-LLaMA/output/llama2/tensorboard"

TRAIN_ITERS=1000
EVAL_ITERS=10
EVAL_INTERVAL=1000
SAVE_INTERVAL=100
LOG_INTERVAL=1

# Setting --tensorboard-queue-size to 1 significantly slows down the training
options=" \
    --finetune \
    --sequence-parallel \
        --tensor-model-parallel-size ${TP_SIZE} \
        --pipeline-model-parallel-size ${PP_SIZE} \
    --num-layers 32 \
        --hidden-size 4096 \
        --num-attention-heads 32 \
        --seq-length 2048 \
        --max-position-embeddings 2048 \
        --no-position-embedding \
        --use-rotary-position-embeddings \
        --swiglu \
        --ffn-hidden-size 11008\
        --disable-bias-linear \
        --RMSNorm \
        --layernorm-epsilon 1e-6 \
        --causal-lm \
    --tokenizer-type PretrainedFromHF \
        --tokenizer-name-or-path $TOKENIZER_PATH \
        --make-vocab-size-divisible-by 1 \
    --init-method-std 0.01 \
    --micro-batch-size ${MICRO_BATCH_SIZE} \
        --global-batch-size ${GLOBAL_BATCH_SIZE} \
    --train-iters ${TRAIN_ITERS} \
    --lr 6.0e-5 \
        --lr-decay-iters 10 \
        --lr-warmup-iters 5 \
        --min-lr 6.0e-6 \
        --override-opt_param-scheduler \
        --lr-decay-style cosine \
    --adam-beta1 0.9 \
        --adam-beta2 0.95 \
        --clip-grad 1.0 \
        --weight-decay 0.1 \
        --overlapped-distributed-optimizer \
        --reduce-bucket-size=2e8 \
        --no-gradient-accumulation-fusion \
    --dataloader-type cyclic \
        --data-impl mmap \
        --data-path ${DATASET} \
        --split 98,2,0 \
    --eval-interval ${EVAL_INTERVAL} \
        --eval-iters ${EVAL_ITERS} \
    --save-interval ${SAVE_INTERVAL} \
        --save ${SAVE_CHECKPOINT_PATH} \
    --load ${LOAD_CHECKPOINT_PATH} \
        --no-load-optim \
    --log-interval ${LOG_INTERVAL} \
    --tensorboard-dir ${TENSORBOARD_DIR} \
        --tensorboard-queue-size 1000 \
        --log-timers-to-tensorboard \
        --log-batch-size-to-tensorboard \
        --log-validation-ppl-to-tensorboard \
    --job-name ${JOB_NAME} \
    --bf16 \
    --recompute-activations \
        --recompute-granularity selective "

torchrun --nnodes 2 --nproc_per_node 2 --rdzv_id=100 --rdzv_backend=c10d --rdzv_endpoint=${MASTER_ADDR}:29400 /code/xx/LLM_mine/reference/Megatron-LLaMA/pretrain_llama.py ${options}

```

**Comment by 13416157913** [comment]
2个节点，每个节点2张卡，能否跑得动lama2-7b吗？这边2个节点，每个节点4张卡跑不动，不知道是不是这边脚本有问题，还是其他原因。

**Comment by Double-bear** [comment]
> 2个节点，每个节点2张卡，能否跑得动lama2-7b吗？这边2个节点，每个节点4张卡跑不动，不知道是不是这边脚本有问题，还是其他原因。

我还没有跑起来，还卡在读模型这里的报错

**Comment by li-yi-dong** [comment]
看起来从hf 转megatron 的时候vocab_size 是32000，但是训练初始化模型的时候，vocab_size 是32002。
你修改过tokenizer 吗？

**Comment by Double-bear** [comment]
> 看起来从hf 转megatron 的时候vocab_size 是32000，但是训练初始化模型的时候，vocab_size 是32002。 你修改过tokenizer 吗？

@li-yi-dong 没有修改过，不过我找到问题是因为我7b的huggingface里多了一个add_token.json的文件，加了一个pad token，导致读取config读的是32001大小，然后在tokenizer里面被padding到了32002，我把add_token的json去了就正常了，不过我发现另一个问题，当我pp设置成2的时候，转完模型load_state_dict的时候load lm_head时会找不到key，然后发现读的那个文pt里确实没有，而是在不同的pt文件中，当我tp=2，pp=2的时候，四个文件只有两个pt有lm_head，不知道是不是我哪里操作有问题？

**Comment by li-yi-dong** [comment]
抱歉，PP暂时没有完整测试过，还有些问题，我们近期会修复。
建议优先使用TP，节省显存更明显，额外开销更小。

**Comment by Double-bear** [comment]
> 抱歉，PP暂时没有完整测试过，还有些问题，我们近期会修复。 建议优先使用TP，节省显存更明显，额外开销更小。

好的好的，谢谢，麻烦你们啦
