### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Double-bear** [alibaba/Megatron-LLaMA#15]
在训练Llama2-7b模型时出现错误：
```
Traceback (most recent call last):

  File "/code/xx/LLM_mine/reference/Megatron-LLaMA/pretrain_llama.py", line 119, in < module >

    pretrain(train_valid_test_datasets_provider, model_provider,

  File "/code/xx/LLM_mine/reference/Megatron-LLaMA/megatron/training.py", line 153, in pretrain

    iteration = train(forward_step_func,

  File "/code/xx/LLM_mine/reference/Megatron-LLaMA/megatron/training.py", line 711, in train

    train_step(forward_step_func,

  File "/code/xx/LLM_mine/reference/Megatron-LLaMA/megatron/training.py", line 426, in train_step

    losses_reduced = forward_backward_func(

  File "/code/xx/LLM_mine/reference/Megatron-LLaMA/megatron/core/pipeline_parallel/schedules.py", line 360, in forward_backward_no_pipelining

    output_tensor = forward_step(forward_step_func, data_iterator,

  File "/code/xx/LLM_mine/reference/Megatron-LLaMA/megatron/core/pipeline_parallel/schedules.py", line 222, in forward_step

    output_tensor = loss_func(output_tensor)

  File "/code/xx/LLM_mine/reference/Megatron-LLaMA/pretrain_llama.py", line 69, in loss_func

    averaged_loss = average_losses_across_data_parallel_group([loss])

  File "/code/xx/LLM_mine/reference/Megatron-LLaMA/megatron/utils.py", line 73, in average_losses_across_data_parallel_group

    torch.distributed.all_reduce(averaged_losses,

  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1536, in all_reduce

    work = group.allreduce([tensor], opts)

RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1670525552843/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1269, internal error, NCCL version 2.14.3

ncclInternalError: Internal check failed.

Last error:

Cuda failure 'device-side assert triggered'

Traceback (most recent call last):

  File "/code/xx/LLM_mine/reference/Megatron-LLaMA/pretrain_llama.py", line 119, in < module >

    pretrain(train_valid_test_datasets_provider, model_provider,

  File "/code/xx/LLM_mine/reference/Megatron-LLaMA/megatron/training.py", line 153, in pretrain

    iteration = train(forward_step_func,

  File "/code/xx/LLM_mine/reference/Megatron-LLaMA/megatron/training.py", line 711, in train

    train_step(forward_step_func,

  File "/code/xx/LLM_mine/reference/Megatron-LLaMA/megatron/training.py", line 426, in train_step

    losses_reduced = forward_backward_func(

  File "/code/xx/LLM_mine/reference/Megatron-LLaMA/megatron/core/pipeline_parallel/schedules.py", line 364, in forward_backward_no_pipelining

    backward_step(grad_scaler, input_tensor, output_tensor,

  File "/code/xx/LLM_mine/reference/Megatron-LLaMA/megatron/core/pipeline_parallel/schedules.py", line 284, in backward_step

    torch.autograd.backward(output_tensor[0], grad_tensors=output_tensor_grad[0])

  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward

    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

RuntimeError: CUDA error: device-side assert triggered

CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.

For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [0,0,0] Assertion `t  >= 0 && t <  n_classes` failed.

/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [2,0,0] Assertion `t  >= 0 && t <  n_classes` failed.

/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [4,0,0] Assertion `t  >= 0 && t <  n_classes` failed.

/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [10,0,0] Assertion `t  >= 0 && t <  n_classes` failed.

/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [11,0,0] Assertion `t  >= 0 && t <  n_classes` failed.

/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [13,0,0] Assertion `t  >= 0 && t <  n_classes` failed.

/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [15,0,0] Assertion `t  >= 0 && t <  n_classes` failed.

/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [16,0,0] Assertion `t  >= 0 && t <  n_classes` failed.

/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [19,0,0] Assertion `t  >= 0 && t <  n_classes` failed.

/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [21,0,0] Assertion `t  >= 0 && t <  n_classes` failed.

/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [22,0,0] Assertion `t  >= 0 && t <  n_classes` failed.

/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [23,0,0] Assertion `t  >= 0 && t <  n_classes` failed.

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 158) of binary: /opt/conda/bin/python

Traceback (most recent call last):

  File "/opt/conda/bin/torchrun", line 33, in < module >

    sys.exit(load_entry_point('torch==1.13.1', 'console_scripts', 'torchrun')())

  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper

    return f(*args, **kwargs)

  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main

    run(args)

  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run

    elastic_launch(

  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__

    return launch_agent(self._config, self._entrypoint, list(args))

  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent

    raise ChildFailedError(

torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```
请教一下这个是什么原因导致的？
提交代码：
```
#!/bin/bash

DATASET_1="/code/xx/LLM_mine/reference/Megatron-LLaMA/data/wiki_zh/wiki_zh_content_document"
DATASET_2="<PATH TO THE SECOND DATASET>"
DATASET_3="<PATH TO THE THIRD DATASET>"
DATASET="1.0 ${DATASET_1}"
# 0.3 ${DATASET_2} 0.5 ${DATASET_3}"

TP_SIZE=2
PP_SIZE=1
WORLD_SIZE=4
MICRO_BATCH_SIZE=2
# The int is the number of micro steps of gradient accumulation
GLOBAL_BATCH_SIZE=$((($WORLD_SIZE * $MICRO_BATCH_SIZE) / ($TP_SIZE * $PP_SIZE) * 8))
# GLOBAL_BATCH_SIZE=128

JOB_NAME="LLaMA_tp${TP_SIZE}_pp${PP_SIZE}_mbs${MICRO_BATCH_SIZE}_gpus${WORLD_SIZE}"

LOAD_CHECKPOINT_PATH="/code/xx/LLM_mine/reference/Megatron-LLaMA/model/llama2-7b"
SAVE_CHECKPOINT_PATH="/code/xx/LLM_mine/reference/Megatron-LLaMA/output/llama2_7b"
TOKENIZER_PATH="/code/xx/LLM_mine/reference/Megatron-LLaMA/model/llama2-7b"
TENSORBOARD_DIR="/code/xx/LLM_mine/reference/Megatron-LLaMA/output"

TRAIN_ITERS=1000
EVAL_ITERS=10
EVAL_INTERVAL=1000
SAVE_INTERVAL=100
LOG_INTERVAL=1

# Setting --tensorboard-queue-size to 1 significantly slows down the training
options=" \
    --finetune \
    --sequence-parallel \
        --tensor-model-parallel-size ${TP_SIZE} \
        --pipeline-model-parallel-size ${PP_SIZE} \
    --num-layers 32 \
        --hidden-size 4096 \
        --num-attention-heads 32 \
        --seq-length 2048 \
        --max-position-embeddings 2048 \
        --no-position-embedding \
        --use-rotary-position-embeddings \
        --swiglu \
        --ffn-hidden-size 11008 \
        --disable-bias-linear \
        --RMSNorm \
        --layernorm-epsilon 1e-6 \
        --causal-lm \
    --tokenizer-type PretrainedFromHF \
        --tokenizer-name-or-path $TOKENIZER_PATH \
        --make-vocab-size-divisible-by 1 \
    --init-method-std 0.01 \
    --micro-batch-size ${MICRO_BATCH_SIZE} \
        --global-batch-size ${GLOBAL_BATCH_SIZE} \
    --train-iters ${TRAIN_ITERS} \
    --lr 6.0e-5 \
        --lr-decay-iters 10 \
        --lr-warmup-iters 5 \
        --min-lr 6.0e-6 \
        --override-opt_param-scheduler \
        --lr-decay-style cosine \
    --adam-beta1 0.9 \
        --adam-beta2 0.95 \
        --clip-grad 1.0 \
        --weight-decay 0.1 \
        --overlapped-distributed-optimizer \
        --reduce-bucket-size=2e8 \
        --no-gradient-accumulation-fusion \
    --dataloader-type cyclic \
        --data-impl mmap \
        --data-path ${DATASET} \
        --split 98,2,0 \
    --eval-interval ${EVAL_INTERVAL} \
        --eval-iters ${EVAL_ITERS} \
    --save-interval ${SAVE_INTERVAL} \
        --save ${SAVE_CHECKPOINT_PATH} \
    --load ${LOAD_CHECKPOINT_PATH} \
        --no-load-optim \
    --log-interval ${LOG_INTERVAL} \
    --tensorboard-dir ${TENSORBOARD_DIR} \
        --tensorboard-queue-size 1000 \
        --log-timers-to-tensorboard \
        --log-batch-size-to-tensorboard \
        --log-validation-ppl-to-tensorboard \
    --job-name ${JOB_NAME} \
    --bf16 \
    --recompute-activations \
        --recompute-granularity selective"

torchrun --nnodes 2 --nproc_per_node 2 --rdzv_id=100 --rdzv_backend=c10d --rdzv_endpoint=${MASTER_ADDR}:29400 /code/xx/LLM_mine/reference/Megatron-LLaMA/pretrain_llama.py ${options}
```

**Comment by XUWeijiang** [comment]
应该是跟我碰到的问题一样，是数据集的问题
https://github.com/alibaba/Megatron-LLaMA/issues/14#issuecomment-1718833918

**Comment by Double-bear** [comment]
> 应该是跟我碰到的问题一样，是数据集的问题 [#14 (comment)](https://github.com/alibaba/Megatron-LLaMA/issues/14#issuecomment-1718960264)

非常感谢！我重新修改一下数据集，请问在转数据的时候--tokenizer-type PretrainedFromHF这样设置，然后--tokenizer-model设置成模型路径（hf分词器跟模型在一个路径下），这样设置是正确的吗？
