### ISSUE TITLE
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead

### ISSUE THREAD

**Issue by 13416157913** [alibaba/Megatron-LLaMA#5]
[before the start of training step] datetime: 2023-09-11 11:26:56
Traceback (most recent call last):
  File "/home/llm-deploy/Megatron-LLaMA/pretrain_llama.py", line 119, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider,
  File "/home/llm-deploy/Megatron-LLaMA/megatron/training.py", line 153, in pretrain
    iteration = train(forward_step_func,
  File "/home/llm-deploy/Megatron-LLaMA/megatron/training.py", line 711, in train
    train_step(forward_step_func,
  File "/home/llm-deploy/Megatron-LLaMA/megatron/training.py", line 426, in train_step
    losses_reduced = forward_backward_func(
  File "/home/llm-deploy/Megatron-LLaMA/megatron/core/pipeline_parallel/schedules.py", line 360, in forward_backward_no_pipelining
    output_tensor = forward_step(forward_step_func, data_iterator,
  File "/home/llm-deploy/Megatron-LLaMA/megatron/core/pipeline_parallel/schedules.py", line 218, in forward_step
    output_tensor, loss_func = forward_step_func(data_iterator, model)
  File "/home/llm-deploy/Megatron-LLaMA/pretrain_llama.py", line 85, in forward_step
    output_tensor = model(tokens, position_ids, attention_mask,
  File "/home/llm-deploy/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/llm-deploy/Megatron-LLaMA/megatron/model/distributed.py", line 58, in forward
    return self.module(*inputs, **kwargs)
  File "/home/llm-deploy/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/llm-deploy/Megatron-LLaMA/megatron/model/module.py", line 183, in forward
    outputs = self.module(*inputs, **kwargs)
  File "/home/llm-deploy/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/llm-deploy/Megatron-LLaMA/megatron/model/llama_model.py", line 113, in forward
    lm_output = self.language_model(
  File "/home/llm-deploy/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/llm-deploy/Megatron-LLaMA/megatron/model/language_model.py", line 520, in forward
    encoder_output = self.encoder(
  File "/home/llm-deploy/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/llm-deploy/Megatron-LLaMA/megatron/model/transformer.py", line 1303, in forward
    hidden_states = layer(
  File "/home/llm-deploy/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/llm-deploy/Megatron-LLaMA/megatron/model/transformer.py", line 792, in forward
    self.self_attention(
  File "/home/llm-deploy/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/llm-deploy/Megatron-LLaMA/megatron/model/transformer.py", line 651, in forward
    context_layer = self._checkpointed_attention_forward(
  File "/home/llm-deploy/Megatron-LLaMA/megatron/model/transformer.py", line 506, in _checkpointed_attention_forward
    hidden_states = tensor_parallel.checkpoint(
  File "/home/llm-deploy/Megatron-LLaMA/megatron/core/tensor_parallel/random.py", line 252, in checkpoint
    return CheckpointFunction.apply(function,
  File "/home/llm-deploy/Megatron-LLaMA/megatron/core/tensor_parallel/random.py", line 195, in forward
    outputs = run_function(*args)
  File "/home/llm-deploy/Megatron-LLaMA/megatron/model/transformer.py", line 499, in custom_forward
    output_ = self.core_attention(query_layer, key_layer,
  File "/home/llm-deploy/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
File "/home/llm-deploy/Megatron-LLaMA/megatron/model/transformer.py", line 315, in forward
    value_layer = value_layer.view(value_layer.size(0),
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead

**Comment by li-yi-dong** [comment]
I'll fix this : )

**Comment by li-yi-dong** [comment]
Fixed by https://code.alibaba-inc.com/openlm/Megatron-Steroid/codereview/13991259
